import json

f = open("rawdata/src_data_filter.json")

data = json.load(f)

rename_map = {
    "Almond butter, creamy" : "Almond Butter",
    "Almond milk, unsweetened, plain, refrigerated" : "Almond Milk",
    "Apples, fuji, with skin, raw" : "Apple",
    "Applesauce, unsweetened, with added vitamin C" : "Applesauce",
    "Apple juice, with added vitamin C, from concentrate, shelf stable": "Apple Juice",
    "Bananas, ripe and slightly ripe, raw": "Bananas",
    "Bananas, overripe, raw": "Bananas",
    "Beans, Dry, Black (0% moisture)" : "Black Beans, Dry",
    "Beans, Dry, Brown (0% moisture)" : "Brown Beans, Dry",
    "Beans, Dry, Carioca (0% moisture" : "Carioca Beans, Dry",
    "Beans, Dry, Cranberry (0% moisture)" : "Cranberry Beans, Dry",
    "Beans, Dry, Dark Red Kidney (0% moisture)" : "Dark Kidney Beans, Dry",
    "Beans, Dry, Flor de Mayo (0% moisture)" : "Flor de Mayo Beans, Dry",
    "Beans, Dry, Great Northern (0% moisture)" : "Great Northern Beans, Dry",
    "Beans, Dry, Light Red Kidney (0% moisture)" : "Light Kidney Beans, Dry",
    "Beans, Dry, Medium Red (0% moisture)" : "Red Beans, Dry",
    "Beans, Dry, Pinto (0% moisture)" :  "Pinto Beans, Dry",
    "Beans, snap, green, canned, regular pack, drained solids" : "Canned Green Beans",
    "Beans, snap, green, raw" : "Green Beans",
    "Beef, ground, 80% lean meat / 20% fat, raw" : "Ground Beef, 80%",
    "Beef, ground, 90% lean meat / 10% fat, raw" : "Ground Beef, 90%",
    "Beef, loin, tenderloin roast, separable lean only, boneless, trimmed to 0\" fat, select, cooked, roasted" : "Beef Tenderlion",
    "Beef, loin, top loin steak, boneless, lip-on, separable lean only, trimmed to 1/8\" fat, choice, raw" : "Top Loin Steak",
    "Beef, round, eye of round roast, boneless, separable lean only, trimmed to 0\" fat, select, raw" : "Eye of Round Roast",
    "Beef, round, top round roast, boneless, separable lean only, trimmed to 0\" fat, select, raw" : "Top Round",
    "Beef, short loin, porterhouse steak, separable lean only, trimmed to 1/8\" fat, select, raw" : "Porterhouse Steak",
    "Beef, short loin, t-bone steak, bone-in, separable lean only, trimmed to 1/8\" fat, choice, cooked, grilled" : "T-Bone Steak",
    "Blueberries, raw" : "Blueberries",
    "Bread, white, commercially prepared": "White Bread",
    "Bread, whole-wheat, commercially prepared": "Wheat Bread",
    "Broccoli, raw": "Broccoli",
    "Buckwheat, whole grain": "Buckwheat",
    "Butter, stick, salted" : "Salted Butter",
    "Butter, stick, unsalted" : "Unsalted Butter",
    "Buttermilk, low fat" : "Buttermilk, 2%",
    "Cabbage, green, raw" : "Green Cabbage",
    "Cabbage, red, raw" : "Red Cabbage",
    "Carrots, baby, raw" : "Baby Carrots",
    "Carrots, mature, raw" : "Carrots",
    "Celery, raw" : "Celery",
    "Cheese, American, restaurant " : "American Cheese",
    "Cheese, cheddar" : "Cheddar Cheese",
    "Cheese, cottage, lowfat, 2% milkfat" : "Cottage Cheese, 2%",
    "Cheese, dry white, queso seco" : "Queso Seco",
    "Cheese, feta, whole milk, crumbled" : "Feta Cheese",
    "Cheese, mozzarella, low moisture, part-skim" : "Mozzarella Cheese",
    "Cheese, parmesan, grated" : "Grated Parmesan Cheese",
    "Cheese, ricotta, whole milk" : "Ricotta Cheese",
    "Cheese, swiss" : "Swiss Cheese",
    "Cherries, sweet, dark red, raw" : "Cherries",
    "Chicken, broiler or fryers, breast, skinless, boneless, meat only, cooked, braised" : "Chicken Breast, Boneless, Skinless",
    "Chicken, broilers or fryers, drumstick, meat only, cooked, braised" : "Chicken Thighs, Boneless, Skinless",
    "Chicken, ground, with additives, raw" : "Ground Chicken",
    "Cookies, oatmeal, soft, with raisins" : "Oatmeal Cookie",
    "Cottage cheese, full fat, large or small curd" : "Cottage Cheese, 4%",
    "Cranberry juice, not fortified, from concentrate, shelf stable" : "Cranberry Juice",
    "Cream cheese, full fat, block" : "Cream Cheese",
    "Cream, heavy" : "Heavy Cream",
    "Cream, sour, full fat" : "Sour Cream",
    "Cucumber, with peel, raw" : "Cucumber",
    "Eggs, Grade A, Large, egg white" : "Egg Whites",
    "Eggs, Grade A, Large, egg whole" : "Eggs",
    "Eggs, Grade A, Large, egg yolk " : "Egg Yolks",
    "Figs, dried, uncooked" : "Figs, Dry",
    "Fish, haddock, raw" : "Haddock",
    "Fish, pollock, raw" : "Pollock",
    "Fish, tuna, light, canned in water, drained solids" : "Canned Tuna in Water",
    "Flaxseed, ground" : "Ground Flaxseed",
    "Flour, almond" : "Almond Flour",
    "Flour, amaranth" : "Amaranth Flour",
    "Flour, barley" : "Barley Flour",
    "Flour, bread, white, enriched, unbleached" : "White Flour",
    "Flour, buckwheat" : "Buckwheat Flour",
    "Flour, cassava" : "Cassava Flour",
    "Flour, chestnut" : "Chessnut Flour",
    "Flour, coconut" : "Coconut Flour",
    "Flour, corn, yellow, fine meal, enriched" : "Corn Flour",
    "Flour, oat, whole grain" : "Oat Flour",
    "Flour, pastry, unenriched, unbleached" : "Pastry Flour",
    "Flour, potato" : "Potato Flour",
    "Flour, quinoa" : "Quinoa Flour",
    "Flour, rice, brown" : "Brown Rice Flour",
    "Flour, rye" : "Rye Flour",
    "Flour, semolina, fine" : "Semolina Flour",
    "Flour, sorghum" : "Sorghum Flour",
    "Flour, soy, full-fat" : "Soy Flour",
    "Flour, spelt, whole grain" : "Spelt Flour",
    "Flour, wheat, all-purpose, enriched, bleached" : "Bleached Wheat Flour",
    "Flour, wheat, all-purpose, unenriched, unbleached" : "Unbleached Wheat Flour",
    "Frankfurter, beef, unheated" : "Frankfurter",
    "Garlic, raw" : "Garlic",
    "Grape juice, purple, with added vitamin C, from concentrate, shelf stable" : "Grape Juice",
    "Grape juice, white, with added vitamin C, from concentrate, shelf stable" : "Grape Juice, White",
    "Grapefruit juice, white, canned or bottled, unsweetened" : "Grapefruit Juice, White",
    "Grapefruit juice, red, not fortified, not from concentrate, refrigerated " : "Grapefruit Juice",
    "Grapes, green, seedless, raw" : "Green Grapes",
    "Grapes, red, seedless, raw" : "Red Grapes",
    "Ham, sliced, pre-packaged, deli meat (96%fat free, water added)" : "Deli Ham",
    "Ham, sliced, restaurant" : "Roast Ham",
    "Hummus, commercial" : "Hummus",
    "Kale, raw" : "Kale",
    "Ketchup, restaurant" : "Ketchup",
    "Kiwifruit, green, raw" : "Kiwifruit",
    "Lettuce, romaine, green, raw" : "Romaine Lettuce",
    "Lettuce, iceberg, raw" : "Iceberg Lettuce",
    "Lettuce, leaf, green, raw" : "Green Lettuce",
    "Lettuce, leaf, red, raw" : "Red Lettuce",
    "Melons, cantaloupe, raw" : "Cantaloupe",
    "Milk, lowfat, fluid, 1% milkfat, with added vitamin A and vitamin D" : "Milk, 1%",
    "Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)" : "Milk, 0%",
    "Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D" : "Milk, 2%",
    "Milk, whole, 3.25% milkfat, with added vitamin D" : "Milk, 4%",
    "Millet, whole grain" : "Millet",
    "Mushroom, beech" : "Beech Mushroom",
    "Mushroom, crimini" : "Crimini Mushroom",
    "Mushroom, enoki" : "Enoki Mushroom",
    "Mushroom, king oyster" : "King Oyster Mushroom",
    "Mushroom, lion's mane" : "Lions mane Mushroom",
    "Mushroom, maitake" : "Maitake Mushroom",
    "Mushroom, oyster" : "Oyster Mushroom",
    "Mushroom, pioppini" : "Pioppini Mushroom",
    "Mushroom, portabella" : "Portabella Mushroom",
    "Mushrooms, shiitake" : "Shiitake Mushroom",
    "Mushrooms, white button" : "White Button Mushroom",
    "Mustard, prepared, yellow" : "Mustard",
    "Nectarines, raw" : "Nectarine",
    "Nuts, almonds, dry roasted, with salt added" : "Almonds, Roasted",
    "Nuts, almonds, whole, raw" : "Almonds",
    "Nuts, brazilnuts, raw" : "Brazilnuts",
    "Nuts, cashew nuts, raw" : "Cashews",
    "Nuts, hazelnuts or filberts, raw" : "Hazelnuts",
    "Nuts, macadamia nuts, raw" : "Macadamia Nuts",
    "Nuts, pecans, halves, raw" : "Pecans",
    "Nuts, pine nuts, raw" : "Pine Nuts",
    "Nuts, pistachio nuts, raw" : "Pistachios",
    "Nuts, walnuts, English, halves, raw" : "Walnuts",
    "Oat milk, unsweetened, plain, refrigerated" : "Oat Milk",
    "Oats, whole grain, rolled, old fashioned" : "Rolled Oats",
    "Oats, whole grain, steel cut" : "Oats",
    "Oil, canola" : "Canola Oil",
    "Oil, coconut" : "Coconut Oil",
    "Oil, corn" : "Corn Oil",
    "Oil, olive, extra light" : "Olive Oil, Light",
    "Oil, olive, extra virgin" : "Olive Oil, Extra Virgin",
    "Oil, peanut" : "Peanut Oil",
    "Oil, safflower" : "Safflower Oil",
    "Oil, soybean" : "Soybean Oil",
    "Oil, sunflower" : "Sunflower Oil",
    "Olives, green, Manzanilla, stuffed with pimiento" : "Green Olives with Pimiento",
    "Onion rings, breaded, par fried, frozen, prepared, heated in oven" : "Onion Rings",
    "Onions, red, raw" : "Red Onion",
    "Onions, white, raw" : "White Onion",
    "Onions, yellow, raw" : "Yellow Onion",
    "Orange juice, no pulp, not fortified, not from concentrate, refrigerated" : "Orange Juice",
    "Oranges, raw, navels" : "Navel Orange",
    "Peaches, yellow, raw" : "Peach",
    "Peanut butter, creamy" : "Peanut Butter",
    "Peanuts, raw" : "Peanuts",
    "Pears, raw, bartlett" : "Bertlett Pears",
    "Peppers, bell, green, raw" : "Green Bell Pepper",
    "Peppers, bell, orange, raw" : "Orange Bell Pepper",
    "Peppers, bell, red, raw" : "Red Bell Pepper",
    "Peppers, bell, yellow, raw" : "Yellow Bell Pepper",
    "Pickles, cucumber, dill or kosher dill" : "Dill Pickle",
    "Pineapple, raw" : "Pineapple",
    "Pork, cured, bacon, cooked, restaurant" : "Bacon",
    "Pork, ground, raw" : "Ground Pork",
    "Potatoes, gold, without skin, raw" : "Gold Potato",
    "Potatoes, red, without skin, raw" : "Red Potato",
    "Potatoes, russet, without skin, raw" : "Russet Potato",
    "Raspberries, raw " : "Raspberries",
    "Restaurant, Chinese, fried rice, without meat " : "Fried Rice",
    "Restaurant, Latino, pupusas con frijoles (pupusas, bean)" : "Pupusas con Frijoles",
    "Restaurant, Latino, tamale, pork" : "Tamale",
    "Rice, brown, long grain, unenriched, raw" : "Brown Rice",
    "Rice, white, long grain, unenriched, raw" : "White Rice",
    "Salt, table, iodized" : "Salt",
    "Sauce, pasta, spaghetti/marinara, ready-to-serve" : "Marinara Sauce",
    "Sauce, salsa, ready-to-serve" : "Salsa",
    "Sausage, Italian, pork, mild, cooked, pan-fried" : "Italian Pork",
    "Sausage, breakfast sausage, beef, pre-cooked, unprepared" : "Beef Breakfast Sausage",
    "Sausage, pork, chorizo, link or ground, cooked, pan-fried" : "Chorizo",
    "Sausage, turkey, breakfast links, mild, raw" : "Turkey Links",
    "Seeds, pumpkin seeds (pepitas), raw" : "Pumpkin Seeds",
    "Seeds, sunflower seed kernels, dry roasted, with salt added" : "Sunflower Seeds",
    "Sesame butter, creamy" : "Sesame Butter",
    "Soy milk, unsweetened, plain, shelf stable " : "Soy Milk",
    "Spinach, baby" : "Spinach, baby",
    "Spinach, mature" : "Spinach",
    "Strawberries, raw" : "Strawberries",
    "Sugars, granulated" : "Granulated Sugar",
    "Sweet potatoes, orange flesh, without skin, raw" : "Sweet Potatoes",
    "Tomato juice, with added ingredients, from concentrate, shelf stable" : "Tomato Juice",
    "Tomato, roma" : "Roma Tomato",
    "Tomatoes, canned, red, ripe, diced" : "Canned Tomato",
    "Tomatoes, grape, raw" : "Grape Tomato",
    "Turkey, ground, 93% lean/ 7% fat, raw" : "Ground Turkey, 7%",
    "Yogurt, Greek, plain, nonfat" : "Greek Yogurt, 1%",
    "Yogurt, Greek, plain, whole milk" : "Greek Yogurt, 4%",
    "Yogurt, plain, whole milk" : "Plain Yogurt"

}

skip_dupes = []

renamed_data = []

for food in data:
    food_temp = food
    
    if food["name"] in rename_map:
        #print(food["name"])
        food_temp["name"] = rename_map[food["name"]]
        if food["name"] not in skip_dupes:
            renamed_data.append(food_temp)
            skip_dupes.append(food["name"])
        else:
            print(food["name"])
    else:
        renamed_data.append(food_temp)
    

w = open("rawdata/src_data_rename.json", "w")
w.write(json.dumps(renamed_data))
f.close()
w.close()
